language: python

branches:
  only:
    - master 

before_script:
  # Decrypt key
  - >
    openssl aes-256-cbc
    -K $encrypted_1f5633e62941_key
    -iv $encrypted_1f5633e62941_iv
    -in .ssh-keys/travis.enc
    -out .ssh-keys/travis
    -d

  # Add the keypair to the agent
  - eval "$(ssh-agent -s)"
  - ssh-add keys/id_rsa

script: true
