{{- if .Values.dash.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dash
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: {{ .Values.dash.httphost }}
    http:
      paths:
      - backend:
          serviceName: dash
          servicePort: dash-http
  - host: {{ .Values.dash.grpchost }}
    http:
      paths:
      - backend:
          serviceName: dash
          servicePort: grpc-proxy-http
{{- end }}