---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: '{{ .Values.etcd.volumeClaim.name }}'
  annotations:
    volume.beta.kubernetes.io/storage-class: "default"
spec:
  accessModes:
    - '{{ .Values.etcd.volumeClaim.accessModes }}'
  resources:
    requests:
      storage: '{{ .Values.etcd.volumeClaim.storage }}'