apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pachd.secretName }}
  labels:
    app: {{ .Values.pachd.secretName }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    suite: pachyderm
data:
  id: {{ .Values.minio.accessKey | b64enc }}
  secret: {{ .Values.minio.secretKey | b64enc }}
  bucket: {{ .Values.minio.bucketName | b64enc }}
  endpoint: {{ (print .Values.minio.releaseName .Values.minio.dom) | b64enc }}
  secure: {{ .Values.minio.secure | b64enc }}