apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pachd.secretName }}
  labels:
    app: {{ .Values.pachd.secretName }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    suite: pachyderm
data:
  minio-id: {{ .Values.minio.accessKey | b64enc }}
  minio-secret: {{ .Values.minio.secretKey | b64enc }}
  minio-bucket: {{ .Values.minio.bucketName | b64enc }}
  minio-endpoint: {{ (print .Values.minio.releaseName .Values.minio.dom) | b64enc }}
  minio-secure: {{ .Values.minio.secure | b64enc }}
