# Default values for a Pachyderm Minio-based deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
pachd:
 secretName: minio-secret
 replicaCount: 1
 volumes:
  volumeName: pachdvol
  secVolName: minio-secret
 resources:
  requests:
   cpu: 1
   memory: 2G
 image:
  repository: pachyderm/pachd
  tag: 1.6.3
  pullPolicy: Always
 worker:
  repository: pachyderm/worker
  tag: 1.6.3

etcd:
 replicaCount: 1
 volumes:
  volumeName: etcdvol
 volumeClaim: 
  name: etcdclaim
  # storageClass: <storageClass>
  storage: 100G
  accessModes: ReadWriteMany
 resources:
  requests:
   cpu: 1
   memory: 2G
 image:
  repository: pachyderm/etcd
  tag: v3.2.7
  pullPolicy: IfNotPresent

minio:
 releaseName: "default"
 dom: "-minio-svc.default.svc.cluster.local:9000"
 bucketName: mybucket
 accessKey: myaccesskey
 secretKey: mysecretkey
 secure: "0"

dash:
 httphost: dash.pach.sv
 grpchost: grpc.pach.sv
 fshost: fs.pach.sv
 enabled: true
 image:
  tag: 0.5.12
  repository: pachyderm/dash
 proxy:
  tag: 0.4.2
  repository: pachyderm/grpc-proxy
